### ISSUE TITLE
Release under a free software/open source license

### ISSUE THREAD

**Issue by twizmwazin** [markplagge/NeMo#56]
Hello! I was made aware of this project by Dr. Carothers in his parallel computing class. In his lecture notes, he described NeMo as open source software, however I was disapointed to find a lack of a license clearly associated with this project. I (and I presume many others) would love to see this project released under a free/open source license. I personally advocate for the GPLv3, however there are many other licenses approved by the OSI, you can find them here: https://opensource.org/licenses/alphabetical

Additionally, GitHub has created a convenient resource for understanding many popular licenses. That can be found at https://choosealicense.com/.

Thank you again!

**Comment by markplagge** [comment]
Boom! We can't do GLPv3 due to linking/grant/library issues, so we've gone for the time being with MIT.

Thanks for the heads up, I'm amazed that we had missed putting the license file in here for so long.

**Comment by twizmwazin** [comment]
Awesome, thanks!
